---
title: "Designing Multi-Layer Graphene-Based Assemblies for Enhanced Toughness in Nacre-Inspired Nanocomposites"
authors: "Xia, W., <b>Song, J.</b>, Meng, Z., & Keten, S." 
journal: "Molecular Systems Design & Engineering"
year: "2016"
volume: "1"
number: "1"
pages: "40-47"
doi: "https://doi.org/10.1021/acs.macromol.6b00121"
pdf: 
arxiv: 
hal: 
image: "/images/MSDE.jpeg"
layout: none
date: 2016-10-01
collection: publications
category: manuscripts
permalink: /publications/sciadv
---


