---
title: "Understanding the Interfacial Mechanical Response of Nanoscale Polymer Thin Films via Nanoindentation"
authors: "Xia, W.&#42;, <b>Song, J.&#42;</b>, Hsu, D. D., & Keten, S." 
journal: "Macromolecules"
year: "2016"
volume: "49"
number: "10"
pages: "3810-3817"
doi: "https://doi.org/10.1021/acs.macromol.6b00121"
pdf: 
arxiv: 
hal: 
image: "/images/Indentation.jpeg"
layout: none
date: 2016-12-01
collection: publications
category: manuscripts
permalink: /publications/sciadv
---

