---
title: "Dynamics of Interacting Interfaces in Polymer Bilayer Thin Films"
authors: "Hsu, D. D., Xia, W., <b>Song, J.</b>, & Keten, S." 
journal: "MRS Communications"
year: "2017"
volume: "7"
number: "4"
pages: "832-839"
doi: "https://doi.org/10.1557/mrc.2017.113"
pdf: 
arxiv: 
hal: 
image: "/images/MRSC.jpg"
layout: none
date: 2017-05-01
collection: publications
category: manuscripts
permalink: /publications/sciadv
---
