---
title: "Side-Group Size Effects on Interfaces and Glass Formation in Supported Polymer Thin Films"
authors: "Xia, W., Song, J., Hsu, D. D., & Keten, S." 
journal: "The Journal of Chemical Physics"
year: "2017"
volume: "146"
number: "20"
pages: "203311"
doi: "https://doi.org/10.1063/1.4976702"
pdf: 
arxiv: 
hal: 
image: "/images/JCP.jpeg"
layout: none
date: 2017-01-01
collection: publications
category: manuscripts
permalink: /publications/sciadv
---
