---
title: "Coarse-Grained Modelling of Polymer Viscoelasticity via Energy Renormalization"
authors: "<b>Song, J.</b>, Hsu, D. D., Shull, K. R., Phelan Jr, F. R., Douglas, J. F., Xia, W., & Keten, S." 
journal: "Macromolecules"
year: "2018"
volume: "51"
number: "10"
pages: "3818-3827"
doi: "https://doi.org/10.1021/acs.macromol.7b02560"
pdf: 
arxiv: 
hal: 
image: "/images/CG11.jpeg"
layout: none
date: 2018-12-01
collection: publications
category: manuscripts
permalink: /publications/sciadv
---

