---
title: "Anti-Fatigue-Fracture Hydrogels"
authors: "Lin, X., Liu, X., Liu, J., Yuk, H., Loh, H., Parada, G. A., Settens, C., <b>Song, J.</b>, Masic, A., McKinley, G. H., & Zhao, X." 
journal: "Science Advances"
year: "2019"
volume: "5"
number: "1"
pages: "eaau8528"
doi: "https://doi.org/10.1126/sciadv.aau8528"
pdf: 
arxiv: 
hal: 
image: "/images/SciAdvXZ2.jpeg"
layout: none
date: 2019-05-01
collection: publications
category: manuscripts
permalink: /publications/sciadv
---
