---
title: "Brush Polymers as Nanoscale Building Blocks for Hydrogel Synthesis"
authors: "Jia, F., <b>Song, J.</b>, Kubiak, J., Santos, P. J., Sano, K., Holten-Andersen, N., Zhang, K., & Macfarlane, R. J."
journal: "Chemistry of Materials"
year: "2021"
volume: "33"
number: "14"
pages: "5748-5756"
doi: "https://doi.org/10.1021/acs.chemmater.1c01585"
pdf: 
arxiv: 
hal: 
image: "/images/ChemMater.png"
layout: none
date: 2021-08-01
collection: publications
category: manuscripts
permalink: /publications/sciadv
---
