---
title: "Non-Maxwellian Viscoelastic Stress Relaxations in Soft Matter"
authors: "<b>Song, J&#42;</b>, Holten-Andersen, N.,  McKinley, G. H."
journal: "Soft Matter"
year: "2023"
volume: "19"
number: 
pages: "7885-7906"
doi: "https://doi.org/10.1039/D3SM00736G"
pdf: 
arxiv: 
hal: 
image: "/images/Review2.png"
layout: none
date: 2023-03-01
collection: publications
category: manuscripts
permalink: /publications/sciadv
---
