---
title: "Strain Stiffening Universality in Composite Hydrogels and Soft Biological Tissues"
authors: "<b>Song, J.</b>, Deiss-Yehiely, E., Yesilata, S., & McKinley, G. H."
journal: "Nature Physics"
year: "2025"
volume: 1-9
number:
pages:
doi: "https://doi.org/10.1038/s41567-025-02869-x"
pdf: 
arxiv: 
hal: 
image: "/images/NPhys.png"
layout: none
date: 2025-02-01
collection: publications
category: manuscripts
permalink: /publications/sciadv
---
