---
title: "Cell-Secreted Extracellular Matrix Mediates Chondrocyte Mechanosensation of Hydrogel Scaffold Viscoelasticity"
authors: "<b>Song, J.</b>, Jones, S., Yang, F., Bhutani, N., Levenston, M. E., & Chaudhuri, O."
journal: 
year: "In Preparation"
volume: 
number: 
pages: 
doi: 
pdf: 
arxiv: 
hal: 
image: "/images/toc_postdoc3.png"
layout: none
date: 2025-01-31
collection: publications
category: manuscripts
permalink: /publications/sciadv
---
