---
title: "Non-linear rheology of melted cheddar cheese"
authors:  "<b>Song, J</b>"
journal: "Journal of Food Engineering
year: "2025"
volume: "391"
number: 
pages: "112450"
doi: "https://doi.org/10.1016/j.jfoodeng.2024.112450"
pdf: "https://jakesong15.github.io/files/publications/cheese.pdf"
arxiv: ""
hal: 
image: "cheese.png"
layout: none
date: 2025-01-01
collection: publications
category: manuscripts
permalink: /publications/cheese
---
